### ISSUE TITLE
Support burning tokens from arbitrary users

### ISSUE THREAD

**Issue by jzxchiang1** [infinity-swap/IS20#40]
The [spec](https://github.com/infinity-swap/IS20/blob/main/spec/IS20.md#burn) says that tokens can be burned from any user specified in the `from` parameter, but the actual canister implementation is more restrictive. It [currently](https://github.com/infinity-swap/IS20/blob/447411b36192519c9b09a7f4ba46faf63b6192c3/src/token/src/canister.rs#L284) only allows burning from the owner's account.

**Comment by Maximkaaa** [comment]
Hi, @jzxchiang1 . Yes, I see the discrepancy between spec and the source code. But I think the source code is correct in this case. I'm not sure if we want to allow the token owner to burn other user's tokens.

Can you please describe your use case for such API?

**Comment by jzxchiang1** [comment]
I suppose the use case is to be able for a user to "stake" their tokens and if some condition is met their stake is "burned".

**Comment by blutooth** [comment]
Fixed
