### ISSUE TITLE
Fix `getUserTransactions`

### ISSUE THREAD

**Issue by jzxchiang1** [infinity-swap/IS20#58]
There are a couple issues with `getUserTransactions`:

- The range [start, start + limit) is supposed to refer to the transactions of the user, but it doesn't. The current implementation refers to the global transaction indices. This makes it impossible to page correctly. (For example, a user could have txn=5 and txn=25 but nothing in between... if the page size is 10, then the client would find that [10, 20) is empty and conclude that the user has no more transactions, which is false.)
- It returns transactions in ascending order of timestamp. But most wallets would actually want to show users their most recent transactions first, so supporting descending order would help a lot.
- `getUserTransactionAmount` is incorrectly documented or incorrectly implemented. It currently returns the total value of all transactions for that user, but the spec says that it instead returns the # of transactions for that user. I'd argue the latter is more useful.

**Comment by blutooth** [comment]
This has been corrected, thank you.
